swagger: '2.0'
info:
  description: Renga Deployer Service.
  version: 1.0.0
  title: Renga Deployer Service
  termsOfService: 'http://datascience.ch/terms/'
  contact:
    email: contact@datascience.ch
  license:
    name: 'Apache License 2.0'
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
host: {{ DEPLOYER_URL }}
basePath: {{ DEPLOYER_BASE_PATH }}
tags:
  - name: Deployer-Contexts
    description: Managing Renga deployment contexts.
  - name: Deployer-Executions
    description: Managing Renga deployment executions.
schemes:
  - http
  - https
paths:
  /contexts:
    get:
      tags:
        - Deployer-Contexts
      summary: List defined contexts.
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contexts'
        '405':
          description: Invalid input
      security:
        - token_auth:
            - 'deployer:contexts_read'
    post:
      tags:
        - Deployer-Contexts
      summary: Create a new context.
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: spec
          description: New context to be added.
          required: true
          schema:
            $ref: '#/definitions/Specification'
      responses:
        '201':
          description: create successful
          schema:
            $ref: '#/definitions/Context'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found
        '405':
          description: Validation exception
      security:
        - token_auth:
            - 'deployer:contexts_write'
            - 'deployer:contexts_read'

  /contexts/{context_id}:
    get:
      tags:
        - Deployer-Contexts
      summary: Find context by ID
      description: Returns a single context
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of context to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Context'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found
      security:
        - token_auth:
            - 'deployer:contexts_read'

  /contexts/{context_id}/executions:
    get:
      tags:
        - Deployer-Executions
      summary: List context executions.
      description: ''
      operationId: renga_deployer.api.contexts.executions.search
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of context to launch
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Executions'
        '405':
          description: Invalid input
      security:
        - token_auth:
            - 'deployer:contexts_read'
            - 'deployer:executions_read'
    post:
      tags:
        - Deployer-Executions
      summary: Execute a context
      operationId: renga_deployer.api.contexts.executions.post
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of context to launch
          required: true
          type: string
        - in: body
          name: data
          description: New execution of a context.
          required: true
          schema:
            $ref: '#/definitions/NewExecution'
      responses:
        '201':
          description: successful operation
          schema:
            $ref: '#/definitions/Execution'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found
      security:
        - token_auth:
            - 'deployer:contexts_read'
            - 'deployer:executions_write'

  /contexts/{context_id}/executions/{execution_id}:
    get:
      tags:
        - Deployer-Executions
      summary: Find execution by ID
      description: Returns a single execution
      operationId: renga_deployer.api.contexts.executions.get
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of execution context
          required: true
          type: string
        - name: execution_id
          in: path
          description: ID of execution to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Execution'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found
      security:
        - token_auth:
            - 'deployer:executions_read'
    delete:
      tags:
        - Deployer-Executions
      summary: Remove an execution
      description: Remove an execution from an engine
      operationId: renga_deployer.api.contexts.executions.delete
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of execution context
          required: true
          type: string
        - name: execution_id
          in: path
          description: ID of execution to remove
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Execution'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found
      security:
        - token_auth:
            - 'deployer:executions_read'
            - 'deployer:executions_write'

  /contexts/{context_id}/executions/{execution_id}/logs:
    get:
      tags:
        - Deployer-Executions
      summary: Fetch the execution logs
      description: Gets the logs from the engine
      operationId: renga_deployer.api.contexts.executions.logs
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of execution context
          required: true
          type: string
        - name: execution_id
          in: path
          description: ID of execution to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: "object"
            properties:
              logs:
                type: "string"
        '400':
          description: Invalid ID supplied
        '404':
          description: Context or execution not found
      security:
        - token_auth:
            - 'deployer:executions_read'

  /contexts/{context_id}/executions/{execution_id}/ports:
    get:
      tags:
        - Deployer-Executions
      summary: Fetch the public host and exposed port of running job
      description: Fetch the public host and exposed port of running job
      operationId: renga_deployer.api.contexts.executions.ports
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of execution context
          required: true
          type: string
        - name: execution_id
          in: path
          description: ID of execution to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: "object"
            properties:
              ports:
                type: "array"
                items:
                  type: "object"
                  properties:
                    specified:
                      type: "string"
                    host:
                      type: "string"
                    protocol:
                      type: "string"
                    exposed:
                      type: "string"
        '400':
          description: Invalid ID supplied
        '404':
          description: Context or execution not found
      security:
        - token_auth:
            - 'deployer:executions_read'

securityDefinitions:
  token_auth:
    type: "oauth2"
    authorizationUrl: "{{ DEPLOYER_AUTHORIZATION_URL }}"
    flow: "implicit"
    scopes:
      deployer:contexts_write: "modify contexts"
      deployer:contexts_read: "read contexts"
      deployer:executions_write: "modify executions"
      deployer:executions_read: "read executions"

definitions:
  Specification:
    type: "object"
    properties:
      image:
        type: "string"
        default: "hello-world"
      ports:
        type: "array"
        items:
          type: "string"
      labels:
        type: "array"
        items:
          type: "string"

  Context:
    type: "object"
    properties:
      identifier:
        type: "string"
      spec:
        $ref: "#/definitions/Specification"

  NewExecution:
    type: "object"
    properties:
      engine:
        type: "string"
        default: "docker"
      namespace:
        type: "string"
        default: "default"

  Execution:
    allOf:
      - $ref: "#/definitions/NewExecution"
      - properties:
          identifier:
            type: "string"

  Contexts:
    type: "object"
    properties:
      contexts:
        type: "array"
        items:
          $ref: '#/definitions/Context'

  Executions:
    type: "object"
    properties:
      executions:
        type: "array"
        items:
          $ref: '#/definitions/Execution'
