swagger: '2.0'
info:
  description: SDSC Deployer Service.
  version: 1.0.0
  title: SDSC Deployer Service
  termsOfService: 'http://datascience.ch/terms/'
  contact:
    email: contact@datascience.ch
  license:
    name: 'Apache License 2.0'
    url: 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html'
host: {{ DEPLOYER_URL }}
basePath: /v1
tags:
  - name: deployer
    description: Everything about deployed contexts.
    externalDocs:
      description: Find out more
      url: 'http://datascience.ch/services/deployer'
schemes:
  - https
paths:
  /contexts:
    get:
      tags:
        - deployer
      summary: List defined contexts.
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contexts'
        '405':
          description: Invalid input
      security:
        - token_auth:
            - 'read:contexts'
    post:
      tags:
        - deployer
      summary: Create a new context.
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: spec
          description: New context to be added.
          required: true
          schema:
            $ref: '#/definitions/Specification'
      responses:
        '201':
          description: create successful
          schema:
            $ref: '#/definitions/Context'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found
        '405':
          description: Validation exception
      security:
        - token_auth:
            - 'write:contexts'
            - 'read:contexts'

  /contexts/{context_id}:
    get:
      tags:
        - deployer
      summary: Find context by ID
      description: Returns a single context
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of context to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Context'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found

  /contexts/{context_id}/executions:
    get:
      tags:
        - deployer
      summary: List context executions.
      description: ''
      operationId: sdsc_deployer.api.contexts.executions.search
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of context to launch
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Executions'
        '405':
          description: Invalid input
      security:
        - token_auth:
            - 'read:contexts'
    post:
      tags:
        - deployer
      summary: Execute a context
      operationId: sdsc_deployer.api.contexts.executions.post
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of context to launch
          required: true
          type: string
        - in: body
          name: data
          description: New execution of a context.
          required: true
          schema:
            $ref: '#/definitions/NewExecution'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Execution'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found

  /contexts/{context_id}/executions/{execution_id}:
    get:
      tags:
        - deployer
      summary: Find execution by ID
      description: Returns a single execution
      operationId: sdsc_deployer.api.contexts.executions.get
      produces:
        - application/json
      parameters:
        - name: context_id
          in: path
          description: ID of execution context
          required: true
          type: string
        - name: execution_id
          in: path
          description: ID of execution to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Execution'
        '400':
          description: Invalid ID supplied
        '404':
          description: context not found

securityDefinitions:
  token_auth:
    type: "oauth2"
    authorizationUrl: "{{ DEPLOYER_AUTHORIZATION_URL }}"
    tokenUrl: "{{ DEPLOYER_TOKEN_URL }}"
    x-tokenInfoUrl: "{{ DEPLOYER_TOKEN_INFO_URL }}"
    flow: "accessCode"
    scopes:
      write:contexts: "modify contexts"
      read:contexts: "read contexts"

definitions:
  Specification:
    type: "object"
    properties:
      image:
        type: "string"
        default: "hello-world"
      ports:
        type: "object"

  Context:
    type: "object"
    properties:
      identifier:
        type: "string"
      spec:
        $ref: "#/definitions/Specification"

  NewExecution:
    type: "object"
    properties:
      engine:
        type: "string"
        default: "docker"
      namespace:
        type: "string"
        default: "default"

  Execution:
    allOf:
      - $ref: "#/definitions/NewExecution"
      - properties:
          identifier:
            type: "string"

  Contexts:
    type: "object"
    properties:
      contexts:
        type: "array"
        items:
          $ref: '#/definitions/Context'

  Executions:
    type: "object"
    properties:
      executions:
        type: "array"
        items:
          $ref: '#/definitions/Execution'
